version: '3'

services:
  database:
    ports:
      - "3307:3306"   
    image: mysql:latest
    environment: 
      MYSQL_ROOT_PASSWORD: password
    networks:
      - some-network
    restart: unless-stopped
    
  client:
    build: ./client    
    container_name: client
    ports:
      - "3000:3000"  
    stdin_open: true
    tty: true
    networks:
      - some-network
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: 
      context: ./server   
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"   
    networks:
      - some-network
    depends_on:
      - database
    restart: unless-stopped

  
networks:
  some-network: {}